/* Icon set: Phosphor (regular weight), exposed under the app's existing names. */
import type { Icon as PhosphorIcon } from '@phosphor-icons/react'
import {
  ArrowSquareOut, Compass, ArrowBendDownRight, ThumbsDown, ThumbsUp, Globe, PlugsConnected, Paperclip, Buildings, Check, Crosshair, Laptop, ArrowsClockwise, Bell, BookOpen, CalendarBlank, CaretDown, CaretUpDown,
  ChartBar, ChatCircle, Clipboard, Clock, Code, Copy, CornersOut,
  DownloadSimple, Export, File, FileText, FolderSimple, FolderSimplePlus, Gavel, Gear,
  GitFork, HardDrives, Image, MagnifyingGlass, Microphone, Minus, Moon, PaperPlaneRight,
  Palette, Plus, Question, Robot, ShieldCheck, SidebarSimple, SlidersHorizontal, Sparkle,
  Stack, Star, Storefront, Sun, Table, TextT, TreeStructure, Flask, X, Graph, ListBullets, Tray,
  ArrowLeft, Lock, PencilSimple, XCircle, Info,
} from '@phosphor-icons/react'

type P = { className?: string }

const I = (Ph: PhosphorIcon) => ({ className }: P) => <Ph className={className} size={20} aria-hidden="true" />

export const IconNewChat = I(Plus)
export const IconProjects = I(FolderSimple)
export const IconAgent = I(Robot)
export const IconWorkflow = I(TreeStructure)
export const IconMarket = I(Storefront)
export const IconResearch = I(Flask)
export const IconApps = I(Stack)
export const IconAdmin = I(ShieldCheck)
export const IconSettings = I(Gear)
export const IconPanel = I(SidebarSimple)
export const IconChevron = I(CaretDown)
export const IconSearch = I(MagnifyingGlass)
export const IconBell = I(Bell)
export const IconHelp = I(Question)
export const IconMic = I(Microphone)
export const IconSend = I(PaperPlaneRight)
export const IconScope = I(File)
export const IconFolderPlus = I(FolderSimplePlus)
export const IconSpark = I(Sparkle)
export const IconMoon = I(Moon)
export const IconClose = I(X)
export const IconSliders = I(SlidersHorizontal)
export const IconChat = I(ChatCircle)
export const IconFork = I(GitFork)
export const IconStar = I(Star)
export const IconGrid = I(Table)
export const IconCode = I(Code)
export const IconBars = I(ChartBar)
export const IconDownload = I(DownloadSimple)
export const IconShare = I(Export)
export const IconSort = I(CaretUpDown)
export const IconFile = I(FileText)
export const IconRecords = I(Clipboard)
export const IconClock = I(Clock)
export const IconFolder = I(FolderSimple)
export const IconSun = I(Sun)
export const IconPalette = I(Palette)
export const IconImage = I(Image)
export const IconRefresh = I(ArrowsClockwise)
export const IconCopy = I(Copy)
export const IconType = I(TextT)
export const IconBook = I(BookOpen)
export const IconServer = I(HardDrives)
export const IconGavel = I(Gavel)
export const IconCalendar = I(CalendarBlank)
export const IconExpand = I(CornersOut)
export const IconPlus = I(Plus)
export const IconMinus = I(Minus)
export const IconExternal = I(ArrowSquareOut)
export const IconOntology = I(Graph)
export const IconList = I(ListBullets)
export const IconInbox = I(Tray)
export const IconTarget = I(Crosshair)
export const IconLocal = I(Laptop)
export const IconOrg = I(Buildings)
export const IconCheck = I(Check)
export const IconAttach = I(Paperclip)
export const IconGlobe = I(Globe)
export const IconPlug = I(PlugsConnected)
export const IconThumbUp = I(ThumbsUp)
export const IconThumbDown = I(ThumbsDown)
export const IconFollow = I(ArrowBendDownRight)
export const IconRoute = I(Compass)
export const IconFeedback = I(ThumbsUp)
export const IconBack = I(ArrowLeft)
export const IconLock = I(Lock)
export const IconEdit = I(PencilSimple)
export const IconError = I(XCircle)
export const IconInfo = I(Info)
